baseurl = "/"
author = "Howard Colin"
title = "Seaman Network, LLC"
languageCode = "en-us"
theme = "foundation-theme"
enableRobotsTXT = true
SectionPagesMenu = ["main", "social"]
name = "Hugof"
license = "MIT"
description = "Seaman Network, LLC"
homepage = "https://seamannetwork.com"
tags = ["network", "hardware"]
features = ["foundation", "hugo", "mobile"]
min_version = 0.17

[params.meta]
description = "Seaman Network, LLC"
keywords = "networking, network, hardware, switch, router, seller"

[params.hero]
herotitle = "Come Together."
herodiscription = "We offer reliable, tested, and budget-friendly computer hardware from every major brand on the market and we are prepared to handle your needs, large or small. So, whether your office needs a complete makeover or a single switch needs a fan, Seaman Network can help. All of our products come with a 1 year warranty (2 years for new equipment) and we also offer a buy-back program for the gear you're replacing. With our one-on-one consultative approach, we want to work with you to determine the best possible solutions to fit your needs."
btnblue = "About Seaman Networking"
btngreen = "Contact Us"

[params.main]
contentOneTitle = "Pardon Our Dust"
contentOneBody = "We're currently revamping our website to better serve you. Please [Contact Us](/contact) for any and all matters."

[params.footer]
phone = "+1 512-843-3503"
email = "gideon@seamannetwork.com"

[[menu.main]]
name = 'Home'
url = "/"

[[menu.main]]
name = "About"
url = "/about"

[[menu.main]]
name = "Contact"
url = "/contact"

[[menu.social]]
name = "Facebook"
url = "http://facebook.com/seamannetwork"

[[menu.social]]
name = "Twitter"
url = "http://twitter.com/seamannetwork"
